=== YatrikChauhan/WebTechnology/web technology/Examples/demo/pract2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="movies">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="movie" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="title" type="xs:string"></xs:element>
						<xs:element name="Release-date" type="xs:date"></xs:element>
						<xs:element name="country" type="xs:string"></xs:element>
						<xs:element name="genre" type="xs:string"></xs:element>
						<xs:element name="Director" type="xs:string"></xs:element>
						<xs:element name="casts">
							<xs:complexType>
							<xs:sequence>
							<xs:element name="Actor" minOccurs="1" maxOccurs="5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="role" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== YatrikChauhan/WebTechnology/web technology/Examples/demo/pract2.xml
<?xml version="1.0"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pract2.xsd">
	<movie>
		<title>Inception</title>
		<Release-date>2010-07-16</Release-date>
		<country>USA</country>
		<genre>Thriller</genre>
		<Director>Christopher_Nolan</Director>
		<casts>
			<Actor>
				<name>Leonardo DiCaprio</name>
				<role>cobb</role>
			</Actor>
			<Actor>
				<name>Ellen Page</name>
				<role>Ariadne</role>
			</Actor>
		</casts>
	</movie>
	<movie>
		<title>Uri</title>
		<Release-date>2019-01-11</Release-date>
		<country>India</country>
		<genre>Thriller</genre>
		<Director>Aditya Dhar</Director>
		<casts>
			<Actor>
				<name>Vicky Kaushal</name>
				<role>Major Vihan</role>
			</Actor>
			<Actor>
				<name>Yami Gautam</name>
				<role>Detective</role>
			</Actor>
			<Actor>
				<name>Paresh Rawal</name>
				<role>Ajit Doval</role>
			</Actor>
		</casts>
	</movie>
</movies>
