=== YatrikChauhan/WebTechnology/web technology/Examples/RemoteSystemsTempFiles/pract1.dtd
<!ELEMENT book-store (book)*>
<!ELEMENT book (title,author,year,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST book category CDATA #REQUIRED>

=== YatrikChauhan/WebTechnology/web technology/Examples/RemoteSystemsTempFiles/pract1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book-store SYSTEM "pract1.dtd">
<book-store>
	<book category="web">
		<title>Web Technology</title>
		<author>Erik T. Ray</author>
		<year>2005</year>
		<price>Rs.250</price>
	</book>
	<book category="Java">
		<title>Advanced Java</title>
		<author>James Gosling</author>
		<year>1998</year>
		<price>Rs.1050</price>
	</book>
	<book category="Dot Net">
		<title>Dot Net with C#</title>
		<author>Anil Prajapati</author>
		<year>2003</year>
		<price>Rs.200</price>
	</book>
</book-store>
